- hosts: all
  gather_facts: true
  environment: "{{ proxy_env }}"
  roles:
    - common
    - git
    - vim
    - poky

- hosts: nfs
  gather_facts: true
  environment: "{{ proxy_env }}"
  roles:
    - nfs-tftp

- hosts: ctf
  gather_facts: true
  environment: "{{ proxy_env }}"
  roles:
    - ctf
