---
- name: Install git, vim and poky packages
  hosts: all
  gather_facts: true
  environment: "{{ proxy_env }}"
  roles:
    - common
    - git
    - vim
    - poky

- name: Install docker
  hosts: all
  gather_facts: true
  environment: "{{ proxy_env }}"
  become: true
  roles:
    - docker

- name: Install nfs and tftp
  hosts: nfs
  gather_facts: true
  environment: "{{ proxy_env }}"
  roles:
    - nfs-tftp

- name: Install packages for ctf
  hosts: ctf
  gather_facts: true
  environment: "{{ proxy_env }}"
  roles:
    - ctf
