---
- name: Install packages for yocto
  ansible.builtin.apt:
    state: present
    update_cache: true
    cache_valid_time: 86400
    pkg:
      - gawk
      - wget
      - git-core
      - diffstat
      - unzip
      - texinfo
      - gcc-multilib
      - build-essential
      - chrpath
      - socat
      - libsdl1.2-dev
      - xterm
      - libncurses5-dev
      - build-essential
      - cpio
      - python3
      - python3-pip
      - python3-pexpect
      - xz-utils
      - debianutils
      - iputils-ping
      - libsdl1.2-dev
      - xterm
      - libssl-dev
      - language-pack-en
  become: true

- name: Check existence of repo command
  ansible.builtin.stat:
    path: ~/bin/repo
  register: repo_bin

- name: Install repo command
  when: not repo_bin.stat.exists
  block:
    - name: Create ~/bin
      ansible.builtin.file:
        path: ~/bin
        mode: "0755"
        state: directory

    - name: Download repo command
      ansible.builtin.get_url:
        url: "http://commondatastorage.googleapis.com/git-repo-downloads/repo"
        dest: ~/bin/repo
        mode: "0755"

    - name: Path to ~/bin
      ansible.builtin.lineinfile:
        path: ~/.bashrc
        line: "export PATH=${PATH}:~/bin"
