---
- name: install packages for yocto
  apt:
    state: present
    update_cache: yes
    cache_valid_time: 86400
    pkg:
      - gawk
      - wget
      - git-core
      - diffstat
      - unzip
      - texinfo
      - gcc-multilib
      - build-essential
      - chrpath
      - socat
      - libsdl1.2-dev
      - xterm
      - libncurses5-dev
      - build-essential
      - cpio
      - python3
      - python3-pip
      - python3-pexpect
      - xz-utils
      - debianutils
      - iputils-ping
      - libsdl1.2-dev
      - xterm
      - libssl-dev
      - language-pack-en
  become: yes
