---
- name: install packages for yocto
  apt: name={{ item }}
  become: yes
  with_items:
    - gawk
    - wget
    - git-core
    - diffstat
    - unzip
    - texinfo
    - gcc-multilib
    - build-essential
    - chrpath
    - socat
    - libsdl1.2-dev
    - xterm
    - libncurses5-dev
    - git
    - build-essential
