---
- name: Install common pkgs
  ansible.builtin.apt:
    state: present
    update_cache: true
    cache_valid_time: 86400
    pkg:
      - build-essential
      - cmake
      - libzip-dev
      - zlib1g-dev
      - qt5-default
      - libqt5svg5-dev
      - qttools5-dev
      - qttools5-dev-tools
      - language-pack-ja
      - tig
      - tree
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
  become: true

- name: Upgrade pip
  ansible.builtin.pip:
    name:
      - pip
      - meson
  become: true

- name: Set timezone to Asia/Tokyo
  community.general.timezone:
    name: Asia/Tokyo
  become: true
