---
- name: Install common pkgs
  ansible.builtin.apt:
    state: present
    update_cache: true
    cache_valid_time: 86400
    pkg:
      - xinetd
      - tftpd-hpa
      - tftp-hpa
      - nfs-kernel-server
  become: true

- name: Create nfs dir
  ansible.builtin.file:
    path: /srv/nfs
    state: directory
    mode: "0777"
  become: true

- name: Create tftp dir
  ansible.builtin.file:
    path: /srv/tftp
    state: directory
    owner: nobody
    mode: "0777"
  become: true
