---
- name: install common pkgs
  apt:
    state: present
    update_cache: true
    cache_valid_time: 86400
    pkg:
      - xinetd
      - tftpd-hpa
      - tftp-hpa
      - nfs-kernel-server
  become: true

- name: create nfs dir
  file:
    path=/srv/nfs
    state=directory
  become: true

- name: create tftp dir
  file:
    path=/srv/tftp
    state=directory
    owner=nobody
    mode=0777
  become: true
