---
- name: install common pkgs
  apt: pkg={{ item }} state=present update_cache=yes cache_valid_time=86400
  with_items:
      - git
      - gcc
      - make
      - vim-nox
      - language-pack-ja-base
      - language-pack-ja
      - tig
      - tree
      - u-boot-tools
      - device-tree-compiler
      - expect
      - bison
      - flex
  become: yes

- name: Check default editor
  stat: path=/etc/alternatives/editor
  register: editor

- name: Set vim-nox as the default editor
  alternatives:
      name: editor
      path: /usr/bin/vim.nox
  when: editor.stat.lnk_source != '/usr/bin/vim.nox'
  become: yes

- name: Set timezone to Asia/Tokyo
  timezone:
    name: Asia/Tokyo
  become: yes
