---
- name: Install common pkgs
  ansible.builtin.apt:
    state: present
    update_cache: true
    cache_valid_time: 86400
    name:
      - git
      - gcc
      - make
      - vim-nox
      - tig
      - tree
      - u-boot-tools
      - device-tree-compiler
      - expect
      - bison
      - flex
      - python3-pip
  become: true

- name: Install language-pack-ja for ubuntu
  ansible.builtin.apt:
    state: present
    update_cache: true
    cache_valid_time: 86400
    name:
      - language-pack-ja
  become: true
  when: ansible_distribution == "Ubuntu"

- name: Check default editor
  ansible.builtin.stat:
    path: /etc/alternatives/editor
  register: editor

- name: Set vim-nox as the default editor
  community.general.alternatives:
    name: editor
    path: /usr/bin/vim.nox
  when: editor.stat.lnk_source != '/usr/bin/vim.nox'
  become: true

- name: Set timezone to Asia/Tokyo
  community.general.timezone:
    name: Asia/Tokyo
  become: true
